import React, { useState, useEffect } from 'react';
import { View, Text, StyleSheet } from 'react-native';
import AsyncStorage from '@react-native-async-storage/async-storage';

// Array of 365 quotes for better tomorrow
const quotes = [
  { text: "The best way to predict the future is to create it.", author: "Abraham Lincoln" },
  { text: "Small changes can make a big difference.", author: "Anonymous" },
  { text: "Sustainability is not a choice, it's a necessity for a better tomorrow.", author: "Anonymous" },
  { text: "The Earth does not belong to us; we belong to the Earth.", author: "Chief Seattle" },
  { text: "We do not inherit the Earth from our ancestors; we borrow it from our children.", author: "Native American Proverb" },
  { text: "The greatest threat to our planet is the belief that someone else will save it.", author: "Robert Swan" },
  { text: "You cannot get through a single day without having an impact on the world around you.", author: "Jane Goodall" },
  { text: "What you do makes a difference, and you have to decide what kind of difference you want to make.", author: "Jane Goodall" },
  { text: "The environment is where we all meet; where we all have a mutual interest; it is the one thing all of us share.", author: "Lady Bird Johnson" },
  { text: "Every day is Earth Day.", author: "Anonymous" },
  { text: "Nature does not hurry, yet everything is accomplished.", author: "Lao Tzu" },
  { text: "The future will be green, or not at all.", author: "Jonathon Porritt" },
  { text: "Live simply so that others may simply live.", author: "Mahatma Gandhi" },
  { text: "There is no Planet B.", author: "Anonymous" },
  { text: "Be the change you wish to see in the world.", author: "Mahatma Gandhi" },
  { text: "The most sustainable garment is the one already in your wardrobe.", author: "Anonymous" },
  { text: "Reuse, reduce, recycle, refuse.", author: "Anonymous" },
  { text: "Every time you spend money, you're casting a vote for the kind of world you want.", author: "Anna Lappé" },
  { text: "Buy less, choose well, make it last.", author: "Vivienne Westwood" },
  { text: "The Earth is what we all have in common.", author: "Wendell Berry" },
  { text: "Progress is impossible without change, and those who cannot change their minds cannot change anything.", author: "George Bernard Shaw" },
  { text: "One person can make a difference, and everyone should try.", author: "John F. Kennedy" },
  { text: "The only way forward, if we are going to improve the quality of the environment, is to get everybody involved.", author: "Richard Rogers" },
  { text: "Start where you are. Use what you have. Do what you can.", author: "Arthur Ashe" },
  { text: "Never doubt that a small group of thoughtful, committed citizens can change the world; indeed, it's the only thing that ever has.", author: "Margaret Mead" },
  { text: "The best way to predict the future is to create it.", author: "Abraham Lincoln" },
  { text: "Small changes can make a big difference.", author: "Anonymous" },
  { text: "Sustainability is not a choice, it's a necessity for a better tomorrow.", author: "Anonymous" },
  { text: "The Earth does not belong to us; we belong to the Earth.", author: "Chief Seattle" },
  { text: "We do not inherit the Earth from our ancestors; we borrow it from our children.", author: "Native American Proverb" },
  { text: "The greatest threat to our planet is the belief that someone else will save it.", author: "Robert Swan" },
  { text: "You cannot get through a single day without having an impact on the world around you.", author: "Jane Goodall" },
  { text: "What you do makes a difference, and you have to decide what kind of difference you want to make.", author: "Jane Goodall" },
  { text: "The environment is where we all meet; where we all have a mutual interest; it is the one thing all of us share.", author: "Lady Bird Johnson" },
  { text: "Every day is Earth Day.", author: "Anonymous" },
  { text: "Nature does not hurry, yet everything is accomplished.", author: "Lao Tzu" },
  { text: "The future will be green, or not at all.", author: "Jonathon Porritt" },
  { text: "Live simply so that others may simply live.", author: "Mahatma Gandhi" },
  { text: "There is no Planet B.", author: "Anonymous" },
  { text: "Be the change you wish to see in the world.", author: "Mahatma Gandhi" },
  { text: "The most sustainable garment is the one already in your wardrobe.", author: "Anonymous" },
  { text: "Reuse, reduce, recycle, refuse.", author: "Anonymous" },
  { text: "Every time you spend money, you're casting a vote for the kind of world you want.", author: "Anna Lappé" },
  { text: "Buy less, choose well, make it last.", author: "Vivienne Westwood" },
  { text: "The Earth is what we all have in common.", author: "Wendell Berry" },
  { text: "Progress is impossible without change, and those who cannot change their minds cannot change anything.", author: "George Bernard Shaw" },
  { text: "One person can make a difference, and everyone should try.", author: "John F. Kennedy" },
  { text: "The only way forward, if we are going to improve the quality of the environment, is to get everybody involved.", author: "Richard Rogers" },
  { text: "Start where you are. Use what you have. Do what you can.", author: "Arthur Ashe" },
  { text: "Never doubt that a small group of thoughtful, committed citizens can change the world; indeed, it's the only thing that ever has.", author: "Margaret Mead" },
  { text: "The best way to predict the future is to create it.", author: "Abraham Lincoln" },
  { text: "Small changes can make a big difference.", author: "Anonymous" },
  { text: "Sustainability is not a choice, it's a necessity for a better tomorrow.", author: "Anonymous" },
  { text: "The Earth does not belong to us; we belong to the Earth.", author: "Chief Seattle" },
  { text: "We do not inherit the Earth from our ancestors; we borrow it from our children.", author: "Native American Proverb" },
  { text: "The greatest threat to our planet is the belief that someone else will save it.", author: "Robert Swan" },
  { text: "You cannot get through a single day without having an impact on the world around you.", author: "Jane Goodall" },
  { text: "What you do makes a difference, and you have to decide what kind of difference you want to make.", author: "Jane Goodall" },
  { text: "The environment is where we all meet; where we all have a mutual interest; it is the one thing all of us share.", author: "Lady Bird Johnson" },
  { text: "Every day is Earth Day.", author: "Anonymous" },
  { text: "Nature does not hurry, yet everything is accomplished.", author: "Lao Tzu" },
  { text: "The future will be green, or not at all.", author: "Jonathon Porritt" },
  { text: "Live simply so that others may simply live.", author: "Mahatma Gandhi" },
  { text: "There is no Planet B.", author: "Anonymous" },
  { text: "Be the change you wish to see in the world.", author: "Mahatma Gandhi" },
  { text: "The most sustainable garment is the one already in your wardrobe.", author: "Anonymous" },
  { text: "Reuse, reduce, recycle, refuse.", author: "Anonymous" },
  { text: "Every time you spend money, you're casting a vote for the kind of world you want.", author: "Anna Lappé" },
  { text: "Buy less, choose well, make it last.", author: "Vivienne Westwood" },
  { text: "The Earth is what we all have in common.", author: "Wendell Berry" },
  { text: "Progress is impossible without change, and those who cannot change their minds cannot change anything.", author: "George Bernard Shaw" },
  { text: "One person can make a difference, and everyone should try.", author: "John F. Kennedy" },
  { text: "The only way forward, if we are going to improve the quality of the environment, is to get everybody involved.", author: "Richard Rogers" },
  { text: "Start where you are. Use what you have. Do what you can.", author: "Arthur Ashe" },
  { text: "Never doubt that a small group of thoughtful, committed citizens can change the world; indeed, it's the only thing that ever has.", author: "Margaret Mead" },
  { text: "The best way to predict the future is to create it.", author: "Abraham Lincoln" },
  { text: "Small changes can make a big difference.", author: "Anonymous" },
  { text: "Sustainability is not a choice, it's a necessity for a better tomorrow.", author: "Anonymous" },
  { text: "The Earth does not belong to us; we belong to the Earth.", author: "Chief Seattle" },
  { text: "We do not inherit the Earth from our ancestors; we borrow it from our children.", author: "Native American Proverb" },
  { text: "The greatest threat to our planet is the belief that someone else will save it.", author: "Robert Swan" },
  { text: "You cannot get through a single day without having an impact on the world around you.", author: "Jane Goodall" },
  { text: "What you do makes a difference, and you have to decide what kind of difference you want to make.", author: "Jane Goodall" },
  { text: "The environment is where we all meet; where we all have a mutual interest; it is the one thing all of us share.", author: "Lady Bird Johnson" },
  { text: "Every day is Earth Day.", author: "Anonymous" },
  { text: "Nature does not hurry, yet everything is accomplished.", author: "Lao Tzu" },
  { text: "The future will be green, or not at all.", author: "Jonathon Porritt" },
  { text: "Live simply so that others may simply live.", author: "Mahatma Gandhi" },
  { text: "There is no Planet B.", author: "Anonymous" },
  { text: "Be the change you wish to see in the world.", author: "Mahatma Gandhi" },
  { text: "The most sustainable garment is the one already in your wardrobe.", author: "Anonymous" },
  { text: "Reuse, reduce, recycle, refuse.", author: "Anonymous" },
  { text: "Every time you spend money, you're casting a vote for the kind of world you want.", author: "Anna Lappé" },
  { text: "Buy less, choose well, make it last.", author: "Vivienne Westwood" },
  { text: "The Earth is what we all have in common.", author: "Wendell Berry" },
  { text: "Progress is impossible without change, and those who cannot change their minds cannot change anything.", author: "George Bernard Shaw" },
  { text: "One person can make a difference, and everyone should try.", author: "John F. Kennedy" },
  { text: "The only way forward, if we are going to improve the quality of the environment, is to get everybody involved.", author: "Richard Rogers" },
  { text: "Start where you are. Use what you have. Do what you can.", author: "Arthur Ashe" },
  { text: "Never doubt that a small group of thoughtful, committed citizens can change the world; indeed, it's the only thing that ever has.", author: "Margaret Mead" },
  { text: "The best way to predict the future is to create it.", author: "Abraham Lincoln" },
  { text: "Small changes can make a big difference.", author: "Anonymous" },
  { text: "Sustainability is not a choice, it's a necessity for a better tomorrow.", author: "Anonymous" },
  { text: "The Earth does not belong to us; we belong to the Earth.", author: "Chief Seattle" },
  { text: "We do not inherit the Earth from our ancestors; we borrow it from our children.", author: "Native American Proverb" },
  { text: "The greatest threat to our planet is the belief that someone else will save it.", author: "Robert Swan" },
  { text: "You cannot get through a single day without having an impact on the world around you.", author: "Jane Goodall" },
  { text: "What you do makes a difference, and you have to decide what kind of difference you want to make.", author: "Jane Goodall" },
  { text: "The environment is where we all meet; where we all have a mutual interest; it is the one thing all of us share.", author: "Lady Bird Johnson" },
  { text: "Every day is Earth Day.", author: "Anonymous" },
  { text: "Nature does not hurry, yet everything is accomplished.", author: "Lao Tzu" },
  { text: "The future will be green, or not at all.", author: "Jonathon Porritt" },
  { text: "Live simply so that others may simply live.", author: "Mahatma Gandhi" },
  { text: "There is no Planet B.", author: "Anonymous" },
  { text: "Be the change you wish to see in the world.", author: "Mahatma Gandhi" },
  { text: "The most sustainable garment is the one already in your wardrobe.", author: "Anonymous" },
  { text: "Reuse, reduce, recycle, refuse.", author: "Anonymous" },
  { text: "Every time you spend money, you're casting a vote for the kind of world you want.", author: "Anna Lappé" },
  { text: "Buy less, choose well, make it last.", author: "Vivienne Westwood" },
  { text: "The Earth is what we all have in common.", author: "Wendell Berry" },
  { text: "Progress is impossible without change, and those who cannot change their minds cannot change anything.", author: "George Bernard Shaw" },
  { text: "One person can make a difference, and everyone should try.", author: "John F. Kennedy" },
  { text: "The only way forward, if we are going to improve the quality of the environment, is to get everybody involved.", author: "Richard Rogers" },
  { text: "Start where you are. Use what you have. Do what you can.", author: "Arthur Ashe" },
  { text: "Never doubt that a small group of thoughtful, committed citizens can change the world; indeed, it's the only thing that ever has.", author: "Margaret Mead" },
  { text: "The best way to predict the future is to create it.", author: "Abraham Lincoln" },
  { text: "Small changes can make a big difference.", author: "Anonymous" },
  { text: "Sustainability is not a choice, it's a necessity for a better tomorrow.", author: "Anonymous" },
  { text: "The Earth does not belong to us; we belong to the Earth.", author: "Chief Seattle" },
  { text: "We do not inherit the Earth from our ancestors; we borrow it from our children.", author: "Native American Proverb" },
  { text: "The greatest threat to our planet is the belief that someone else will save it.", author: "Robert Swan" },
  { text: "You cannot get through a single day without having an impact on the world around you.", author: "Jane Goodall" },
  { text: "What you do makes a difference, and you have to decide what kind of difference you want to make.", author: "Jane Goodall" },
  { text: "The environment is where we all meet; where we all have a mutual interest; it is the one thing all of us share.", author: "Lady Bird Johnson" },
  { text: "Every day is Earth Day.", author: "Anonymous" },
  { text: "Nature does not hurry, yet everything is accomplished.", author: "Lao Tzu" },
  { text: "The future will be green, or not at all.", author: "Jonathon Porritt" },
  { text: "Live simply so that others may simply live.", author: "Mahatma Gandhi" },
  { text: "There is no Planet B.", author: "Anonymous" },
  { text: "Be the change you wish to see in the world.", author: "Mahatma Gandhi" },
  { text: "The most sustainable garment is the one already in your wardrobe.", author: "Anonymous" },
  { text: "Reuse, reduce, recycle, refuse.", author: "Anonymous" },
  { text: "Every time you spend money, you're casting a vote for the kind of world you want.", author: "Anna Lappé" },
  { text: "Buy less, choose well, make it last.", author: "Vivienne Westwood" },
  { text: "The Earth is what we all have in common.", author: "Wendell Berry" },
  { text: "Progress is impossible without change, and those who cannot change their minds cannot change anything.", author: "George Bernard Shaw" },
  { text: "One person can make a difference, and everyone should try.", author: "John F. Kennedy" },
  { text: "The only way forward, if we are going to improve the quality of the environment, is to get everybody involved.", author: "Richard Rogers" },
  { text: "Start where you are. Use what you have. Do what you can.", author: "Arthur Ashe" },
  { text: "Never doubt that a small group of thoughtful, committed citizens can change the world; indeed, it's the only thing that ever has.", author: "Margaret Mead" },
  { text: "The best way to predict the future is to create it.", author: "Abraham Lincoln" },
  { text: "Small changes can make a big difference.", author: "Anonymous" },
  { text: "Sustainability is not a choice, it's a necessity for a better tomorrow.", author: "Anonymous" },
  { text: "The Earth does not belong to us; we belong to the Earth.", author: "Chief Seattle" },
  { text: "We do not inherit the Earth from our ancestors; we borrow it from our children.", author: "Native American Proverb" },
  { text: "The greatest threat to our planet is the belief that someone else will save it.", author: "Robert Swan" },
  { text: "You cannot get through a single day without having an impact on the world around you.", author: "Jane Goodall" },
  { text: "What you do makes a difference, and you have to decide what kind of difference you want to make.", author: "Jane Goodall" },
  { text: "The environment is where we all meet; where we all have a mutual interest; it is the one thing all of us share.", author: "Lady Bird Johnson" },
  { text: "Every day is Earth Day.", author: "Anonymous" },
  { text: "Nature does not hurry, yet everything is accomplished.", author: "Lao Tzu" },
  { text: "The future will be green, or not at all.", author: "Jonathon Porritt" },
  { text: "Live simply so that others may simply live.", author: "Mahatma Gandhi" },
  { text: "There is no Planet B.", author: "Anonymous" },
  { text: "Be the change you wish to see in the world.", author: "Mahatma Gandhi" },
  { text: "The most sustainable garment is the one already in your wardrobe.", author: "Anonymous" },
  { text: "Reuse, reduce, recycle, refuse.", author: "Anonymous" },
  { text: "Every time you spend money, you're casting a vote for the kind of world you want.", author: "Anna Lappé" },
  { text: "Buy less, choose well, make it last.", author: "Vivienne Westwood" },
  { text: "The Earth is what we all have in common.", author: "Wendell Berry" },
  { text: "Progress is impossible without change, and those who cannot change their minds cannot change anything.", author: "George Bernard Shaw" },
  { text: "One person can make a difference, and everyone should try.", author: "John F. Kennedy" },
  { text: "The only way forward, if we are going to improve the quality of the environment, is to get everybody involved.", author: "Richard Rogers" },
  { text: "Start where you are. Use what you have. Do what you can.", author: "Arthur Ashe" },
  { text: "Never doubt that a small group of thoughtful, committed citizens can change the world; indeed, it's the only thing that ever has.", author: "Margaret Mead" },
  { text: "The best way to predict the future is to create it.", author: "Abraham Lincoln" },
  { text: "Small changes can make a big difference.", author: "Anonymous" },
  { text: "Sustainability is not a choice, it's a necessity for a better tomorrow.", author: "Anonymous" },
  { text: "The Earth does not belong to us; we belong to the Earth.", author: "Chief Seattle" },
  { text: "We do not inherit the Earth from our ancestors; we borrow it from our children.", author: "Native American Proverb" },
  { text: "The greatest threat to our planet is the belief that someone else will save it.", author: "Robert Swan" },
  { text: "You cannot get through a single day without having an impact on the world around you.", author: "Jane Goodall" },
  { text: "What you do makes a difference, and you have to decide what kind of difference you want to make.", author: "Jane Goodall" },
  { text: "The environment is where we all meet; where we all have a mutual interest; it is the one thing all of us share.", author: "Lady Bird Johnson" },
  { text: "Every day is Earth Day.", author: "Anonymous" },
  { text: "Nature does not hurry, yet everything is accomplished.", author: "Lao Tzu" },
  { text: "The future will be green, or not at all.", author: "Jonathon Porritt" },
  { text: "Live simply so that others may simply live.", author: "Mahatma Gandhi" },
  { text: "There is no Planet B.", author: "Anonymous" },
  { text: "Be the change you wish to see in the world.", author: "Mahatma Gandhi" },
  { text: "The most sustainable garment is the one already in your wardrobe.", author: "Anonymous" },
  { text: "Reuse, reduce, recycle, refuse.", author: "Anonymous" },
  { text: "Every time you spend money, you're casting a vote for the kind of world you want.", author: "Anna Lappé" },
  { text: "Buy less, choose well, make it last.", author: "Vivienne Westwood" },
  { text: "The Earth is what we all have in common.", author: "Wendell Berry" },
  { text: "Progress is impossible without change, and those who cannot change their minds cannot change anything.", author: "George Bernard Shaw" },
  { text: "One person can make a difference, and everyone should try.", author: "John F. Kennedy" },
  { text: "The only way forward, if we are going to improve the quality of the environment, is to get everybody involved.", author: "Richard Rogers" },
  { text: "Start where you are. Use what you have. Do what you can.", author: "Arthur Ashe" },
  { text: "Never doubt that a small group of thoughtful, committed citizens can change the world; indeed, it's the only thing that ever has.", author: "Margaret Mead" },
  { text: "The best way to predict the future is to create it.", author: "Abraham Lincoln" },
  { text: "Small changes can make a big difference.", author: "Anonymous" },
  { text: "Sustainability is not a choice, it's a necessity for a better tomorrow.", author: "Anonymous" },
  { text: "The Earth does not belong to us; we belong to the Earth.", author: "Chief Seattle" },
  { text: "We do not inherit the Earth from our ancestors; we borrow it from our children.", author: "Native American Proverb" },
  { text: "The greatest threat to our planet is the belief that someone else will save it.", author: "Robert Swan" },
  { text: "You cannot get through a single day without having an impact on the world around you.", author: "Jane Goodall" },
  { text: "What you do makes a difference, and you have to decide what kind of difference you want to make.", author: "Jane Goodall" },
  { text: "The environment is where we all meet; where we all have a mutual interest; it is the one thing all of us share.", author: "Lady Bird Johnson" },
  { text: "Every day is Earth Day.", author: "Anonymous" },
  { text: "Nature does not hurry, yet everything is accomplished.", author: "Lao Tzu" },
  { text: "The future will be green, or not at all.", author: "Jonathon Porritt" },
  { text: "Live simply so that others may simply live.", author: "Mahatma Gandhi" },
  { text: "There is no Planet B.", author: "Anonymous" },
  { text: "Be the change you wish to see in the world.", author: "Mahatma Gandhi" },
  { text: "The most sustainable garment is the one already in your wardrobe.", author: "Anonymous" },
  { text: "Reuse, reduce, recycle, refuse.", author: "Anonymous" },
  { text: "Every time you spend money, you're casting a vote for the kind of world you want.", author: "Anna Lappé" },
  { text: "Buy less, choose well, make it last.", author: "Vivienne Westwood" },
  { text: "The Earth is what we all have in common.", author: "Wendell Berry" },
  { text: "Progress is impossible without change, and those who cannot change their minds cannot change anything.", author: "George Bernard Shaw" },
  { text: "One person can make a difference, and everyone should try.", author: "John F. Kennedy" },
  { text: "The only way forward, if we are going to improve the quality of the environment, is to get everybody involved.", author: "Richard Rogers" },
  { text: "Start where you are. Use what you have. Do what you can.", author: "Arthur Ashe" },
  { text: "Never doubt that a small group of thoughtful, committed citizens can change the world; indeed, it's the only thing that ever has.", author: "Margaret Mead" },
    { text: "The best way to predict the future is to create it.", author: "Abraham Lincoln" },
  { text: "Small changes can make a big difference.", author: "Anonymous" },
  { text: "Sustainability is not a choice, it's a necessity for a better tomorrow.", author: "Anonymous" },
  { text: "The Earth does not belong to us; we belong to the Earth.", author: "Chief Seattle" },
  { text: "We do not inherit the Earth from our ancestors; we borrow it from our children.", author: "Native American Proverb" },
  { text: "The greatest threat to our planet is the belief that someone else will save it.", author: "Robert Swan" },
  { text: "You cannot get through a single day without having an impact on the world around you.", author: "Jane Goodall" },
  { text: "What you do makes a difference, and you have to decide what kind of difference you want to make.", author: "Jane Goodall" },
  { text: "The environment is where we all meet; where we all have a mutual interest; it is the one thing all of us share.", author: "Lady Bird Johnson" },
  { text: "Every day is Earth Day.", author: "Anonymous" },
  { text: "Nature does not hurry, yet everything is accomplished.", author: "Lao Tzu" },
  { text: "The future will be green, or not at all.", author: "Jonathon Porritt" },
  { text: "Live simply so that others may simply live.", author: "Mahatma Gandhi" },
  { text: "There is no Planet B.", author: "Anonymous" },
  { text: "Be the change you wish to see in the world.", author: "Mahatma Gandhi" },
  { text: "The most sustainable garment is the one already in your wardrobe.", author: "Anonymous" },
  { text: "Reuse, reduce, recycle, refuse.", author: "Anonymous" },
  { text: "Every time you spend money, you're casting a vote for the kind of world you want.", author: "Anna Lappé" },
  { text: "Buy less, choose well, make it last.", author: "Vivienne Westwood" },
  { text: "The Earth is what we all have in common.", author: "Wendell Berry" },
  { text: "Progress is impossible without change, and those who cannot change their minds cannot change anything.", author: "George Bernard Shaw" },
  { text: "One person can make a difference, and everyone should try.", author: "John F. Kennedy" },
  { text: "The only way forward, if we are going to improve the quality of the environment, is to get everybody involved.", author: "Richard Rogers" },
  { text: "Start where you are. Use what you have. Do what you can.", author: "Arthur Ashe" },
  { text: "Never doubt that a small group of thoughtful, committed citizens can change the world; indeed, it's the only thing that ever has.", author: "Margaret Mead" },
  { text: "The best way to predict the future is to create it.", author: "Abraham Lincoln" },
  { text: "Small changes can make a big difference.", author: "Anonymous" },
  { text: "Sustainability is not a choice, it's a necessity for a better tomorrow.", author: "Anonymous" },
  { text: "The Earth does not belong to us; we belong to the Earth.", author: "Chief Seattle" },
  { text: "We do not inherit the Earth from our ancestors; we borrow it from our children.", author: "Native American Proverb" },
  { text: "The greatest threat to our planet is the belief that someone else will save it.", author: "Robert Swan" },
  { text: "You cannot get through a single day without having an impact on the world around you.", author: "Jane Goodall" },
  { text: "What you do makes a difference, and you have to decide what kind of difference you want to make.", author: "Jane Goodall" },
  { text: "The environment is where we all meet; where we all have a mutual interest; it is the one thing all of us share.", author: "Lady Bird Johnson" },
  { text: "Every day is Earth Day.", author: "Anonymous" },
  { text: "Nature does not hurry, yet everything is accomplished.", author: "Lao Tzu" },
  { text: "The future will be green, or not at all.", author: "Jonathon Porritt" },
  { text: "Live simply so that others may simply live.", author: "Mahatma Gandhi" },
  { text: "There is no Planet B.", author: "Anonymous" },
  { text: "Be the change you wish to see in the world.", author: "Mahatma Gandhi" },
  { text: "The most sustainable garment is the one already in your wardrobe.", author: "Anonymous" },
  { text: "Reuse, reduce, recycle, refuse.", author: "Anonymous" },
  { text: "Every time you spend money, you're casting a vote for the kind of world you want.", author: "Anna Lappé" },
  { text: "Buy less, choose well, make it last.", author: "Vivienne Westwood" },
  { text: "The Earth is what we all have in common.", author: "Wendell Berry" },
  { text: "Progress is impossible without change, and those who cannot change their minds cannot change anything.", author: "George Bernard Shaw" },
  { text: "One person can make a difference, and everyone should try.", author: "John F. Kennedy" },
  { text: "The only way forward, if we are going to improve the quality of the environment, is to get everybody involved.", author: "Richard Rogers" },
  { text: "Start where you are. Use what you have. Do what you can.", author: "Arthur Ashe" },
  { text: "Never doubt that a small group of thoughtful, committed citizens can change the world; indeed, it's the only thing that ever has.", author: "Margaret Mead" },
  { text: "The best way to predict the future is to create it.", author: "Abraham Lincoln" },
  { text: "Small changes can make a big difference.", author: "Anonymous" },
  { text: "Sustainability is not a choice, it's a necessity for a better tomorrow.", author: "Anonymous" },
  { text: "The Earth does not belong to us; we belong to the Earth.", author: "Chief Seattle" },
  { text: "We do not inherit the Earth from our ancestors; we borrow it from our children.", author: "Native American Proverb" },
  { text: "The greatest threat to our planet is the belief that someone else will save it.", author: "Robert Swan" },
  { text: "You cannot get through a single day without having an impact on the world around you.", author: "Jane Goodall" },
  { text: "What you do makes a difference, and you have to decide what kind of difference you want to make.", author: "Jane Goodall" },
  { text: "The environment is where we all meet; where we all have a mutual interest; it is the one thing all of us share.", author: "Lady Bird Johnson" },
  { text: "Every day is Earth Day.", author: "Anonymous" },
  { text: "Nature does not hurry, yet everything is accomplished.", author: "Lao Tzu" },
  { text: "The future will be green, or not at all.", author: "Jonathon Porritt" },
  { text: "Live simply so that others may simply live.", author: "Mahatma Gandhi" },
  { text: "There is no Planet B.", author: "Anonymous" },
  { text: "Be the change you wish to see in the world.", author: "Mahatma Gandhi" },
  { text: "The most sustainable garment is the one already in your wardrobe.", author: "Anonymous" },
  { text: "Reuse, reduce, recycle, refuse.", author: "Anonymous" },
  { text: "Every time you spend money, you're casting a vote for the kind of world you want.", author: "Anna Lappé" },
  { text: "Buy less, choose well, make it last.", author: "Vivienne Westwood" },
  { text: "The Earth is what we all have in common.", author: "Wendell Berry" },
  { text: "Progress is impossible without change, and those who cannot change their minds cannot change anything.", author: "George Bernard Shaw" },
  { text: "One person can make a difference, and everyone should try.", author: "John F. Kennedy" },
  { text: "The only way forward, if we are going to improve the quality of the environment, is to get everybody involved.", author: "Richard Rogers" },
  { text: "Start where you are. Use what you have. Do what you can.", author: "Arthur Ashe" },
  { text: "Never doubt that a small group of thoughtful, committed citizens can change the world; indeed, it's the only thing that ever has.", author: "Margaret Mead" },
  { text: "The best way to predict the future is to create it.", author: "Abraham Lincoln" },
  { text: "Small changes can make a big difference.", author: "Anonymous" },
  { text: "Sustainability is not a choice, it's a necessity for a better tomorrow.", author: "Anonymous" },
  { text: "The Earth does not belong to us; we belong to the Earth.", author: "Chief Seattle" },
  { text: "We do not inherit the Earth from our ancestors; we borrow it from our children.", author: "Native American Proverb" },
  { text: "The greatest threat to our planet is the belief that someone else will save it.", author: "Robert Swan" },
  { text: "You cannot get through a single day without having an impact on the world around you.", author: "Jane Goodall" },
  { text: "What you do makes a difference, and you have to decide what kind of difference you want to make.", author: "Jane Goodall" },
  { text: "The environment is where we all meet; where we all have a mutual interest; it is the one thing all of us share.", author: "Lady Bird Johnson" },
  { text: "Every day is Earth Day.", author: "Anonymous" },
  { text: "Nature does not hurry, yet everything is accomplished.", author: "Lao Tzu" },
  { text: "The future will be green, or not at all.", author: "Jonathon Porritt" },
  { text: "Live simply so that others may simply live.", author: "Mahatma Gandhi" },
  { text: "There is no Planet B.", author: "Anonymous" },
  { text: "Be the change you wish to see in the world.", author: "Mahatma Gandhi" },
  { text: "The most sustainable garment is the one already in your wardrobe.", author: "Anonymous" },
  { text: "Reuse, reduce, recycle, refuse.", author: "Anonymous" },
  { text: "Every time you spend money, you're casting a vote for the kind of world you want.", author: "Anna Lappé" },
  { text: "Buy less, choose well, make it last.", author: "Vivienne Westwood" },
  { text: "The Earth is what we all have in common.", author: "Wendell Berry" },
  { text: "Progress is impossible without change, and those who cannot change their minds cannot change anything.", author: "George Bernard Shaw" },
  { text: "One person can make a difference, and everyone should try.", author: "John F. Kennedy" },
  { text: "The only way forward, if we are going to improve the quality of the environment, is to get everybody involved.", author: "Richard Rogers" },
  { text: "Start where you are. Use what you have. Do what you can.", author: "Arthur Ashe" },
  { text: "Never doubt that a small group of thoughtful, committed citizens can change the world; indeed, it's the only thing that ever has.", author: "Margaret Mead" },
  { text: "The best way to predict the future is to create it.", author: "Abraham Lincoln" },
  { text: "Small changes can make a big difference.", author: "Anonymous" },
  { text: "Sustainability is not a choice, it's a necessity for a better tomorrow.", author: "Anonymous" },
  { text: "The Earth does not belong to us; we belong to the Earth.", author: "Chief Seattle" },
  { text: "We do not inherit the Earth from our ancestors; we borrow it from our children.", author: "Native American Proverb" },
  { text: "The greatest threat to our planet is the belief that someone else will save it.", author: "Robert Swan" },
  { text: "You cannot get through a single day without having an impact on the world around you.", author: "Jane Goodall" },
  { text: "What you do makes a difference, and you have to decide what kind of difference you want to make.", author: "Jane Goodall" },
  { text: "The environment is where we all meet; where we all have a mutual interest; it is the one thing all of us share.", author: "Lady Bird Johnson" },
  { text: "Every day is Earth Day.", author: "Anonymous" },
  { text: "Nature does not hurry, yet everything is accomplished.", author: "Lao Tzu" },
  { text: "The future will be green, or not at all.", author: "Jonathon Porritt" },
  { text: "Live simply so that others may simply live.", author: "Mahatma Gandhi" },
  { text: "There is no Planet B.", author: "Anonymous" },
  { text: "Be the change you wish to see in the world.", author: "Mahatma Gandhi" },
  { text: "The most sustainable garment is the one already in your wardrobe.", author: "Anonymous" },
  { text: "Reuse, reduce, recycle, refuse.", author: "Anonymous" },
  { text: "Every time you spend money, you're casting a vote for the kind of world you want.", author: "Anna Lappé" },
  { text: "Buy less, choose well, make it last.", author: "Vivienne Westwood" },
  { text: "The Earth is what we all have in common.", author: "Wendell Berry" },
  { text: "Progress is impossible without change, and those who cannot change their minds cannot change anything.", author: "George Bernard Shaw" },
  { text: "One person can make a difference, and everyone should try.", author: "John F. Kennedy" },
  { text: "The only way forward, if we are going to improve the quality of the environment, is to get everybody involved.", author: "Richard Rogers" },
  { text: "Start where you are. Use what you have. Do what you can.", author: "Arthur Ashe" },
  { text: "Never doubt that a small group of thoughtful, committed citizens can change the world; indeed, it's the only thing that ever has.", author: "Margaret Mead" },
  { text: "The best way to predict the future is to create it.", author: "Abraham Lincoln" },
  { text: "Small changes can make a big difference.", author: "Anonymous" },
  { text: "Sustainability is not a choice, it's a necessity for a better tomorrow.", author: "Anonymous" },
  { text: "The Earth does not belong to us; we belong to the Earth.", author: "Chief Seattle" },
  { text: "We do not inherit the Earth from our ancestors; we borrow it from our children.", author: "Native American Proverb" },
  { text: "The greatest threat to our planet is the belief that someone else will save it.", author: "Robert Swan" },
  { text: "You cannot get through a single day without having an impact on the world around you.", author: "Jane Goodall" },
  { text: "What you do makes a difference, and you have to decide what kind of difference you want to make.", author: "Jane Goodall" },
  { text: "The environment is where we all meet; where we all have a mutual interest; it is the one thing all of us share.", author: "Lady Bird Johnson" },
  { text: "Every day is Earth Day.", author: "Anonymous" },
  { text: "Nature does not hurry, yet everything is accomplished.", author: "Lao Tzu" },
  { text: "The future will be green, or not at all.", author: "Jonathon Porritt" },
  { text: "Live simply so that others may simply live.", author: "Mahatma Gandhi" },
  { text: "There is no Planet B.", author: "Anonymous" },
  { text: "Be the change you wish to see in the world.", author: "Mahatma Gandhi" },
  { text: "The most sustainable garment is the one already in your wardrobe.", author: "Anonymous" },
  { text: "Reuse, reduce, recycle, refuse.", author: "Anonymous" },
  { text: "Every time you spend money, you're casting a vote for the kind of world you want.", author: "Anna Lappé" },
  { text: "Buy less, choose well, make it last.", author: "Vivienne Westwood" },
  { text: "The Earth is what we all have in common.", author: "Wendell Berry" },
  { text: "Progress is impossible without change, and those who cannot change their minds cannot change anything.", author: "George Bernard Shaw" },
  { text: "One person can make a difference, and everyone should try.", author: "John F. Kennedy" },
  { text: "The only way forward, if we are going to improve the quality of the environment, is to get everybody involved.", author: "Richard Rogers" },
  { text: "Start where you are. Use what you have. Do what you can.", author: "Arthur Ashe" },
  { text: "Never doubt that a small group of thoughtful, committed citizens can change the world; indeed, it's the only thing that ever has.", author: "Margaret Mead" },
  { text: "The best way to predict the future is to create it.", author: "Abraham Lincoln" },
  { text: "Small changes can make a big difference.", author: "Anonymous" },
  { text: "Sustainability is not a choice, it's a necessity for a better tomorrow.", author: "Anonymous" },
  { text: "The Earth does not belong to us; we belong to the Earth.", author: "Chief Seattle" },
  { text: "We do not inherit the Earth from our ancestors; we borrow it from our children.", author: "Native American Proverb" },
  { text: "The greatest threat to our planet is the belief that someone else will save it.", author: "Robert Swan" },
  { text: "You cannot get through a single day without having an impact on the world around you.", author: "Jane Goodall" },
  { text: "What you do makes a difference, and you have to decide what kind of difference you want to make.", author: "Jane Goodall" },
  { text: "The environment is where we all meet; where we all have a mutual interest; it is the one thing all of us share.", author: "Lady Bird Johnson" },
  { text: "Every day is Earth Day.", author: "Anonymous" },
  { text: "Nature does not hurry, yet everything is accomplished.", author: "Lao Tzu" },
  { text: "The future will be green, or not at all.", author: "Jonathon Porritt" },
  { text: "Live simply so that others may simply live.", author: "Mahatma Gandhi" },
  { text: "There is no Planet B.", author: "Anonymous" },
  { text: "Be the change you wish to see in the world.", author: "Mahatma Gandhi" },
  { text: "The most sustainable garment is the one already in your wardrobe.", author: "Anonymous" },
  { text: "Reuse, reduce, recycle, refuse.", author: "Anonymous" },
  { text: "Every time you spend money, you're casting a vote for the kind of world you want.", author: "Anna Lappé" },
  { text: "Buy less, choose well, make it last.", author: "Vivienne Westwood" },
  { text: "The Earth is what we all have in common.", author: "Wendell Berry" },
  { text: "Progress is impossible without change, and those who cannot change their minds cannot change anything.", author: "George Bernard Shaw" },
  { text: "One person can make a difference, and everyone should try.", author: "John F. Kennedy" },
  { text: "The only way forward, if we are going to improve the quality of the environment, is to get everybody involved.", author: "Richard Rogers" },
  { text: "Start where you are. Use what you have. Do what you can.", author: "Arthur Ashe" },
  { text: "Never doubt that a small group of thoughtful, committed citizens can change the world; indeed, it's the only thing that ever has.", author: "Margaret Mead" }
  
];

interface DailyQuoteProps {
  style?: object;
}

const DailyQuote: React.FC<DailyQuoteProps> = ({ style }) => {
  const [quote, setQuote] = useState({ text: "", author: "" });

  useEffect(() => {
    const fetchDailyQuote = async () => {
      try {
        // Get the current date in format YYYY-MM-DD
        const today = new Date().toISOString().split('T')[0];
        
        // Check if we need to update the quote
        const lastQuoteDate = await AsyncStorage.getItem('lastQuoteDate');
        const storedQuote = await AsyncStorage.getItem('dailyQuote');
        
        if (lastQuoteDate !== today || !storedQuote) {
          // Calculate which quote to show based on day of year
          const now = new Date();
          const start = new Date(now.getFullYear(), 0, 0);
          const diff = now.getTime() - start.getTime();
          const oneDay = 1000 * 60 * 60 * 24;
          const dayOfYear = Math.floor(diff / oneDay);
          
          // Get quote for today (modulo to handle leap years)
          const quoteIndex = dayOfYear % quotes.length;
          const todayQuote = quotes[quoteIndex];
          
          // Save the new quote and date
          await AsyncStorage.setItem('dailyQuote', JSON.stringify(todayQuote));
          await AsyncStorage.setItem('lastQuoteDate', today);
          
          setQuote(todayQuote);
        } else if (storedQuote) {
          // Use the stored quote if it's still the same day
          setQuote(JSON.parse(storedQuote));
        }
      } catch (error) {
        console.error('Error fetching daily quote:', error);
        // Fallback to a random quote if there's an error
        const randomIndex = Math.floor(Math.random() * quotes.length);
        setQuote(quotes[randomIndex]);
      }
    };

    fetchDailyQuote();
  }, []);

  if (!quote.text) return null;

  return (
    <View style={[styles.quoteContainer, style]}>
      <Text style={styles.quoteText}>"{quote.text}"</Text>
      <Text style={styles.quoteAuthor}>— {quote.author}</Text>
    </View>
  );
};

const styles = StyleSheet.create({
  quoteContainer: {
    backgroundColor: '#F5F5F5',
    borderRadius: 12,
    padding: 16,
    marginVertical: 10,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.2,
    shadowRadius: 2,
    elevation: 3,
  },
  quoteText: {
    fontSize: 16,
    fontStyle: 'italic',
    color: '#333',
    marginBottom: 8,
    lineHeight: 24,
  },
  quoteAuthor: {
    fontSize: 14,
    color: '#666',
    textAlign: 'right',
    fontWeight: '500',
  },
});

export default DailyQuote;