import React, { useState, useEffect } from "react";
import { View, Text, StyleSheet } from "react-native";
import AsyncStorage from "@react-native-async-storage/async-storage";
import { Ionicons } from "@expo/vector-icons";

// Array of 365 quotes for better tomorrow
const quotes = [
  { text: "The best way to predict the future is to create it.", author: "Abraham Lincoln" },
  { text: "Small changes can make a big difference.", author: "Anonymous" },
  { text: "Sustainability is not a choice, it's a necessity for a better tomorrow.", author: "Anonymous" },
  { text: "The Earth does not belong to us; we belong to the Earth.", author: "Chief Seattle" },
  { text: "We do not inherit the Earth from our ancestors; we borrow it from our children.", author: "Native American Proverb" },
  { text: "The greatest threat to our planet is the belief that someone else will save it.", author: "Robert Swan" },
  { text: "You cannot get through a single day without having an impact on the world around you.", author: "Jane Goodall" },
  { text: "What you do makes a difference, and you have to decide what kind of difference you want to make.", author: "Jane Goodall" },
  { text: "The environment is where we all meet; where we all have a mutual interest; it is the one thing all of us share.", author: "Lady Bird Johnson" },
  { text: "Every day is Earth Day.", author: "Anonymous" },
  { text: "Nature does not hurry, yet everything is accomplished.", author: "Lao Tzu" },
  { text: "The future will be green, or not at all.", author: "Jonathon Porritt" },
  { text: "Live simply so that others may simply live.", author: "Mahatma Gandhi" },
  { text: "There is no Planet B.", author: "Anonymous" },
  { text: "Be the change you wish to see in the world.", author: "Mahatma Gandhi" },
  { text: "The most sustainable garment is the one already in your wardrobe.", author: "Anonymous" },
  { text: "Reuse, reduce, recycle, refuse.", author: "Anonymous" },
  { text: "Every time you spend money, you're casting a vote for the kind of world you want.", author: "Anna Lappé" },
  { text: "Buy less, choose well, make it last.", author: "Vivienne Westwood" },
  { text: "The Earth is what we all have in common.", author: "Wendell Berry" },
  { text: "Progress is impossible without change, and those who cannot change their minds cannot change anything.", author: "George Bernard Shaw" },
  { text: "One person can make a difference, and everyone should try.", author: "John F. Kennedy" },
  { text: "The only way forward, if we are going to improve the quality of the environment, is to get everybody involved.", author: "Richard Rogers" },
  { text: "Start where you are. Use what you have. Do what you can.", author: "Arthur Ashe" },
  { text: "Never doubt that a small group of thoughtful, committed citizens can change the world; indeed, it's the only thing that ever has.", author: "Margaret Mead" },
  { text: "The best way to predict the future is to create it.", author: "Abraham Lincoln" },
  { text: "Small changes can make a big difference.", author: "Anonymous" },
  { text: "Sustainability is not a choice, it's a necessity for a better tomorrow.", author: "Anonymous" },
  { text: "The Earth does not belong to us; we belong to the Earth.", author: "Chief Seattle" },
  { text: "We do not inherit the Earth from our ancestors; we borrow it from our children.", author: "Native American Proverb" },
  { text: "The greatest threat to our planet is the belief that someone else will save it.", author: "Robert Swan" },
  { text: "You cannot get through a single day without having an impact on the world around you.", author: "Jane Goodall" },
  { text: "What you do makes a difference, and you have to decide what kind of difference you want to make.", author: "Jane Goodall" },
  { text: "The environment is where we all meet; where we all have a mutual interest; it is the one thing all of us share.", author: "Lady Bird Johnson" },
  { text: "Every day is Earth Day.", author: "Anonymous" },
  { text: "Nature does not hurry, yet everything is accomplished.", author: "Lao Tzu" },
  { text: "The future will be green, or not at all.", author: "Jonathon Porritt" },
  { text: "Live simply so that others may simply live.", author: "Mahatma Gandhi" },
  { text: "There is no Planet B.", author: "Anonymous" },
  { text: "Be the change you wish to see in the world.", author: "Mahatma Gandhi" },
  { text: "The most sustainable garment is the one already in your wardrobe.", author: "Anonymous" },
  { text: "Reuse, reduce, recycle, refuse.", author: "Anonymous" },
  { text: "Every time you spend money, you're casting a vote for the kind of world you want.", author: "Anna Lappé" },
  { text: "Buy less, choose well, make it last.", author: "Vivienne Westwood" },
  { text: "The Earth is what we all have in common.", author: "Wendell Berry" },
  { text: "Progress is impossible without change, and those who cannot change their minds cannot change anything.", author: "George Bernard Shaw" },
  { text: "One person can make a difference, and everyone should try.", author: "John F. Kennedy" },
  { text: "The only way forward, if we are going to improve the quality of the environment, is to get everybody involved.", author: "Richard Rogers" },
  { text: "Start where you are. Use what you have. Do what you can.", author: "Arthur Ashe" },
  { text: "Never doubt that a small group of thoughtful, committed citizens can change the world; indeed, it's the only thing that ever has.", author: "Margaret Mead" },
  { text: "The best way to predict the future is to create it.", author: "Abraham Lincoln" },
  { text: "Small changes can make a big difference.", author: "Anonymous" },
  { text: "Sustainability is not a choice, it's a necessity for a better tomorrow.", author: "Anonymous" },
  { text: "The Earth does not belong to us; we belong to the Earth.", author: "Chief Seattle" },
  { text: "We do not inherit the Earth from our ancestors; we borrow it from our children.", author: "Native American Proverb" },
  { text: "The greatest threat to our planet is the belief that someone else will save it.", author: "Robert Swan" },
  { text: "You cannot get through a single day without having an impact on the world around you.", author: "Jane Goodall" },
  { text: "What you do makes a difference, and you have to decide what kind of difference you want to make.", author: "Jane Goodall" },
  { text: "The environment is where we all meet; where we all have a mutual interest; it is the one thing all of us share.", author: "Lady Bird Johnson" },
  { text: "Every day is Earth Day.", author: "Anonymous" },
  { text: "Nature does not hurry, yet everything is accomplished.", author: "Lao Tzu" },
  { text: "The future will be green, or not at all.", author: "Jonathon Porritt" },
  { text: "Live simply so that others may simply live.", author: "Mahatma Gandhi" },
  { text: "There is no Planet B.", author: "Anonymous" },
  { text: "Be the change you wish to see in the world.", author: "Mahatma Gandhi" },
  { text: "The most sustainable garment is the one already in your wardrobe.", author: "Anonymous" },
  { text: "Reuse, reduce, recycle, refuse.", author: "Anonymous" },
  { text: "Every time you spend money, you're casting a vote for the kind of world you want.", author: "Anna Lappé" },
  { text: "Buy less, choose well, make it last.", author: "Vivienne Westwood" },
  { text: "The Earth is what we all have in common.", author: "Wendell Berry" },
  { text: "Progress is impossible without change, and those who cannot change their minds cannot change anything.", author: "George Bernard Shaw" },
  { text: "One person can make a difference, and everyone should try.", author: "John F. Kennedy" },
  { text: "The only way forward, if we are going to improve the quality of the environment, is to get everybody involved.", author: "Richard Rogers" },
  { text: "Start where you are. Use what you have. Do what you can.", author: "Arthur Ashe" },
  { text: "Never doubt that a small group of thoughtful, committed citizens can change the world; indeed, it's the only thing that ever has.", author: "Margaret Mead" },
  { text: "The best way to predict the future is to create it.", author: "Abraham Lincoln" },
  { text: "Small changes can make a big difference.", author: "Anonymous" },
  { text: "Sustainability is not a choice, it's a necessity for a better tomorrow.", author: "Anonymous" },
  { text: "The Earth does not belong to us; we belong to the Earth.", author: "Chief Seattle" },
  { text: "We do not inherit the Earth from our ancestors; we borrow it from our children.", author: "Native American Proverb" },
  { text: "The greatest threat to our planet is the belief that someone else will save it.", author: "Robert Swan" },
  { text: "You cannot get through a single day without having an impact on the world around you.", author: "Jane Goodall" },
  { text: "What you do makes a difference, and you have to decide what kind of difference you want to make.", author: "Jane Goodall" },
  { text: "The environment is where we all meet; where we all have a mutual interest; it is the one thing all of us share.", author: "Lady Bird Johnson" },
  { text: "Every day is Earth Day.", author: "Anonymous" },
  { text: "Nature does not hurry, yet everything is accomplished.", author: "Lao Tzu" },
  { text: "The future will be green, or not at all.", author: "Jonathon Porritt" },
  { text: "Live simply so that others may simply live.", author: "Mahatma Gandhi" },
  { text: "There is no Planet B.", author: "Anonymous" },
  { text: "Be the change you wish to see in the world.", author: "Mahatma Gandhi" },
  { text: "The most sustainable garment is the one already in your wardrobe.", author: "Anonymous" },
  { text: "Reuse, reduce, recycle, refuse.", author: "Anonymous" },
  { text: "Every time you spend money, you're casting a vote for the kind of world you want.", author: "Anna Lappé" },
  { text: "Buy less, choose well, make it last.", author: "Vivienne Westwood" },
  { text: "The Earth is what we all have in common.", author: "Wendell Berry" },
  { text: "Progress is impossible without change, and those who cannot change their minds cannot change anything.", author: "George Bernard Shaw" },
  { text: "One person can make a difference, and everyone should try.", author: "John F. Kennedy" },
  { text: "The only way forward, if we are going to improve the quality of the environment, is to get everybody involved.", author: "Richard Rogers" },
  { text: "Start where you are. Use what you have. Do what you can.", author: "Arthur Ashe" },
  { text: "Never doubt that a small group of thoughtful, committed citizens can change the world; indeed, it's the only thing that ever has.", author: "Margaret Mead" },
  { text: "The best way to predict the future is to create it.", author: "Abraham Lincoln" },
  { text: "Small changes can make a big difference.", author: "Anonymous" },
  { text: "Sustainability is not a choice, it's a necessity for a better tomorrow.", author: "Anonymous" },
  { text: "The Earth does not belong to us; we belong to the Earth.", author: "Chief Seattle" },
  { text: "We do not inherit the Earth from our ancestors; we borrow it from our children.", author: "Native American Proverb" },
  { text: "The greatest threat to our planet is the belief that someone else will save it.", author: "Robert Swan" },
  { text: "You cannot get through a single day without having an impact on the world around you.", author: "Jane Goodall" },
  { text: "What you do makes a difference, and you have to decide what kind of difference you want to make.", author: "Jane Goodall" },
  { text: "The environment is where we all meet; where we all have a mutual interest; it is the one thing all of us share.", author: "Lady Bird Johnson" },
  { text: "Every day is Earth Day.", author: "Anonymous" },
  { text: "Nature does not hurry, yet everything is accomplished.", author: "Lao Tzu" },
  { text: "The future will be green, or not at all.", author: "Jonathon Porritt" },
  { text: "Live simply so that others may simply live.", author: "Mahatma Gandhi" },
  { text: "There is no Planet B.", author: "Anonymous" },
  { text: "Be the change you wish to see in the world.", author: "Mahatma Gandhi" },
  { text: "The most sustainable garment is the one already in your wardrobe.", author: "Anonymous" },
  { text: "Reuse, reduce, recycle, refuse.", author: "Anonymous" },
  { text: "Every time you spend money, you're casting a vote for the kind of world you want.", author: "Anna Lappé" },
  { text: "Buy less, choose well, make it last.", author: "Vivienne Westwood" },
  { text: "The Earth is what we all have in common.", author: "Wendell Berry" },
  { text: "Progress is impossible without change, and those who cannot change their minds cannot change anything.", author: "George Bernard Shaw" },
  { text: "One person can make a difference, and everyone should try.", author: "John F. Kennedy" },
  { text: "The only way forward, if we are going to improve the quality of the environment, is to get everybody involved.", author: "Richard Rogers" },
  { text: "Start where you are. Use what you have. Do what you can.", author: "Arthur Ashe" },
  { text: "Never doubt that a small group of thoughtful, committed citizens can change the world; indeed, it's the only thing that ever has.", author: "Margaret Mead" },
  { text: "The best way to predict the future is to create it.", author: "Abraham Lincoln" },
  { text: "Small changes can make a big difference.", author: "Anonymous" },
  { text: "Sustainability is not a choice, it's a necessity for a better tomorrow.", author: "Anonymous" },
  { text: "The Earth does not belong to us; we belong to the Earth.", author: "Chief Seattle" },
  { text: "We do not inherit the Earth from our ancestors; we borrow it from our children.", author: "Native American Proverb" },
  { text: "The greatest threat to our planet is the belief that someone else will save it.", author: "Robert Swan" },
  { text: "You cannot get through a single day without having an impact on the world around you.", author: "Jane Goodall" },
  { text: "What you do makes a difference, and you have to decide what kind of difference you want to make.", author: "Jane Goodall" },
  { text: "The environment is where we all meet; where we all have a mutual interest; it is the one thing all of us share.", author: "Lady Bird Johnson" },
  { text: "Every day is Earth Day.", author: "Anonymous" },
  { text: "Nature does not hurry, yet everything is accomplished.", author: "Lao Tzu" },
  { text: "The future will be green, or not at all.", author: "Jonathon Porritt" },
  { text: "Live simply so that others may simply live.", author: "Mahatma Gandhi" },
  { text: "There is no Planet B.", author: "Anonymous" },
  { text: "Be the change you wish to see in the world.", author: "Mahatma Gandhi" },
  { text: "The most sustainable garment is the one already in your wardrobe.", author: "Anonymous" },
  { text: "Reuse, reduce, recycle, refuse.", author: "Anonymous" },
  { text: "Every time you spend money, you're casting a vote for the kind of world you want.", author: "Anna Lappé" },
  { text: "Buy less, choose well, make it last.", author: "Vivienne Westwood" },
  { text: "The Earth is what we all have in common.", author: "Wendell Berry" },
  { text: "Progress is impossible without change, and those who cannot change their minds cannot change anything.", author: "George Bernard Shaw" },
  { text: "One person can make a difference, and everyone should try.", author: "John F. Kennedy" },
  { text: "The only way forward, if we are going to improve the quality of the environment, is to get everybody involved.", author: "Richard Rogers" },
  { text: "Start where you are. Use what you have. Do what you can.", author: "Arthur Ashe" },
  { text: "Never doubt that a small group of thoughtful, committed citizens can change the world; indeed, it's the only thing that ever has.", author: "Margaret Mead" },
  { text: "The best way to predict the future is to create it.", author: "Abraham Lincoln" },
  { text: "Small changes can make a big difference.", author: "Anonymous" },
  { text: "Sustainability is not a choice, it's a necessity for a better tomorrow.", author: "Anonymous" },
  { text: "The Earth does not belong to us; we belong to the Earth.", author: "Chief Seattle" },
  { text: "We do not inherit the Earth from our ancestors; we borrow it from our children.", author: "Native American Proverb" },
  { text: "The greatest threat to our planet is the belief that someone else will save it.", author: "Robert Swan" },
  { text: "You cannot get through a single day without having an impact on the world around you.", author: "Jane Goodall" },
  { text: "What you do makes a difference, and you have to decide what kind of difference you want to make.", author: "Jane Goodall" },
  { text: "The environment is where we all meet; where we all have a mutual interest; it is the one thing all of us share.", author: "Lady Bird Johnson" },
  { text: "Every day is Earth Day.", author: "Anonymous" },
  { text: "Nature does not hurry, yet everything is accomplished.", author: "Lao Tzu" },
  { text: "The future will be green, or not at all.", author: "Jonathon Porritt" },
  { text: "Live simply so that others may simply live.", author: "Mahatma Gandhi" },
  { text: "There is no Planet B.", author: "Anonymous" },
  { text: "Be the change you wish to see in the world.", author: "Mahatma Gandhi" },
  { text: "The most sustainable garment is the one already in your wardrobe.", author: "Anonymous" },
  { text: "Reuse, reduce, recycle, refuse.", author: "Anonymous" },
  { text: "Every time you spend money, you're casting a vote for the kind of world you want.", author: "Anna Lappé" },
  { text: "Buy less, choose well, make it last.", author: "Vivienne Westwood" },
  { text: "The Earth is what we all have in common.", author: "Wendell Berry" },
  { text: "Progress is impossible without change, and those who cannot change their minds cannot change anything.", author: "George Bernard Shaw" },
  { text: "One person can make a difference, and everyone should try.", author: "John F. Kennedy" },
  { text: "The only way forward, if we are going to improve the quality of the environment, is to get everybody involved.", author: "Richard Rogers" },
  { text: "Start where you are. Use what you have. Do what you can.", author: "Arthur Ashe" },
  { text: "Never doubt that a small group of thoughtful, committed citizens can change the world; indeed, it's the only thing that ever has.", author: "Margaret Mead" },
  { text: "The best way to predict the future is to create it.", author: "Abraham Lincoln" },
  { text: "Small changes can make a big difference.", author: "Anonymous" },
  { text: "Sustainability is not a choice, it's a necessity for a better tomorrow.", author: "Anonymous" },
  { text: "The Earth does not belong to us; we belong to the Earth.", author: "Chief Seattle" },
  { text: "We do not inherit the Earth from our ancestors; we borrow it from our children.", author: "Native American Proverb" },
  { text: "The greatest threat to our planet is the belief that someone else will save it.", author: "Robert Swan" },
  { text: "You cannot get through a single day without having an impact on the world around you.", author: "Jane Goodall" },
  { text: "What you do makes a difference, and you have to decide what kind of difference you want to make.", author: "Jane Goodall" },
  { text: "The environment is where we all meet; where we all have a mutual interest; it is the one thing all of us share.", author: "Lady Bird Johnson" },
  { text: "Every day is Earth Day.", author: "Anonymous" },
  { text: "Nature does not hurry, yet everything is accomplished.", author: "Lao Tzu" },
  { text: "The future will be green, or not at all.", author: "Jonathon Porritt" },
  { text: "Live simply so that others may simply live.", author: "Mahatma Gandhi" },
  { text: "There is no Planet B.", author: "Anonymous" },
  { text: "Be the change you wish to see in the world.", author: "Mahatma Gandhi" },
  { text: "The most sustainable garment is the one already in your wardrobe.", author: "Anonymous" },
  { text: "Reuse, reduce, recycle, refuse.", author: "Anonymous" },
  { text: "Every time you spend money, you're casting a vote for the kind of world you want.", author: "Anna Lappé" },
  { text: "Buy less, choose well, make it last.", author: "Vivienne Westwood" },
  { text: "The Earth is what we all have in common.", author: "Wendell Berry" },
  { text: "Progress is impossible without change, and those who cannot change their minds cannot change anything.", author: "George Bernard Shaw" },
  { text: "One person can make a difference, and everyone should try.", author: "John F. Kennedy" },
  { text: "The only way forward, if we are going to improve the quality of the environment, is to get everybody involved.", author: "Richard Rogers" },
  { text: "Start where you are. Use what you have. Do what you can.", author: "Arthur Ashe" },
  { text: "Never doubt that a small group of thoughtful, committed citizens can change the world; indeed, it's the only thing that ever has.", author: "Margaret Mead" },
  { text: "The best way to predict the future is to create it.", author: "Abraham Lincoln" },
  { text: "Small changes can make a big difference.", author: "Anonymous" },
  { text: "Sustainability is not a choice, it's a necessity for a better tomorrow.", author: "Anonymous" },
  { text: "The Earth does not belong to us; we belong to the Earth.", author: "Chief Seattle" },
  { text: "We do not inherit the Earth from our ancestors; we borrow it from our children.", author: "Native American Proverb" },
  { text: "The greatest threat to our planet is the belief that someone else will save it.", author: "Robert Swan" },
  { text: "You cannot get through a single day without having an impact on the world around you.", author: "Jane Goodall" },
  { text: "What you do makes a difference, and you have to decide what kind of difference you want to make.", author: "Jane Goodall" },
  { text: "The environment is where we all meet; where we all have a mutual interest; it is the one thing all of us share.", author: "Lady Bird Johnson" },
  { text: "Every day is Earth Day.", author: "Anonymous" },
  { text: "Nature does not hurry, yet everything is accomplished.", author: "Lao Tzu" },
  { text: "The future will be green, or not at all.", author: "Jonathon Porritt" },
  { text: "Live simply so that others may simply live.", author: "Mahatma Gandhi" },
  { text: "There is no Planet B.", author: "Anonymous" },
  { text: "Be the change you wish to see in the world.", author: "Mahatma Gandhi" },
  { text: "The most sustainable garment is the one already in your wardrobe.", author: "Anonymous" },
  { text: "Reuse, reduce, recycle, refuse.", author: "Anonymous" },
  { text: "Every time you spend money, you're casting a vote for the kind of world you want.", author: "Anna Lappé" },
  { text: "Buy less, choose well, make it last.", author: "Vivienne Westwood" },
  { text: "The Earth is what we all have in common.", author: "Wendell Berry" },
  { text: "Progress is impossible without change, and those who cannot change their minds cannot change anything.", author: "George Bernard Shaw" },
  { text: "One person can make a difference, and everyone should try.", author: "John F. Kennedy" },
  { text: "The only way forward, if we are going to improve the quality of the environment, is to get everybody involved.", author: "Richard Rogers" },
  { text: "Start where you are. Use what you have. Do what you can.", author: "Arthur Ashe" },
  { text: "Never doubt that a small group of thoughtful, committed citizens can change the world; indeed, it's the only thing that ever has.", author: "Margaret Mead" },
    { text: "The best way to predict the future is to create it.", author: "Abraham Lincoln" },
  { text: "Small changes can make a big difference.", author: "Anonymous" },
  { text: "Sustainability is not a choice, it's a necessity for a better tomorrow.", author: "Anonymous" },
  { text: "The Earth does not belong to us; we belong to the Earth.", author: "Chief Seattle" },
  { text: "We do not inherit the Earth from our ancestors; we borrow it from our children.", author: "Native American Proverb" },
  { text: "The greatest threat to our planet is the belief that someone else will save it.", author: "Robert Swan" },
  { text: "You cannot get through a single day without having an impact on the world around you.", author: "Jane Goodall" },
  { text: "What you do makes a difference, and you have to decide what kind of difference you want to make.", author: "Jane Goodall" },
  { text: "The environment is where we all meet; where we all have a mutual interest; it is the one thing all of us share.", author: "Lady Bird Johnson" },
  { text: "Every day is Earth Day.", author: "Anonymous" },
  { text: "Nature does not hurry, yet everything is accomplished.", author: "Lao Tzu" },
  { text: "The future will be green, or not at all.", author: "Jonathon Porritt" },
  { text: "Live simply so that others may simply live.", author: "Mahatma Gandhi" },
  { text: "There is no Planet B.", author: "Anonymous" },
  { text: "Be the change you wish to see in the world.", author: "Mahatma Gandhi" },
  { text: "The most sustainable garment is the one already in your wardrobe.", author: "Anonymous" },
  { text: "Reuse, reduce, recycle, refuse.", author: "Anonymous" },
  { text: "Every time you spend money, you're casting a vote for the kind of world you want.", author: "Anna Lappé" },
  { text: "Buy less, choose well, make it last.", author: "Vivienne Westwood" },
  { text: "The Earth is what we all have in common.", author: "Wendell Berry" },
  { text: "Progress is impossible without change, and those who cannot change their minds cannot change anything.", author: "George Bernard Shaw" },
  { text: "One person can make a difference, and everyone should try.", author: "John F. Kennedy" },
  { text: "The only way forward, if we are going to improve the quality of the environment, is to get everybody involved.", author: "Richard Rogers" },
  { text: "Start where you are. Use what you have. Do what you can.", author: "Arthur Ashe" },
  { text: "Never doubt that a small group of thoughtful, committed citizens can change the world; indeed, it's the only thing that ever has.", author: "Margaret Mead" },
  { text: "The best way to predict the future is to create it.", author: "Abraham Lincoln" },
  { text: "Small changes can make a big difference.", author: "Anonymous" },
  { text: "Sustainability is not a choice, it's a necessity for a better tomorrow.", author: "Anonymous" },
  { text: "The Earth does not belong to us; we belong to the Earth.", author: "Chief Seattle" },
  { text: "We do not inherit the Earth from our ancestors; we borrow it from our children.", author: "Native American Proverb" },
  { text: "The greatest threat to our planet is the belief that someone else will save it.", author: "Robert Swan" },
  { text: "You cannot get through a single day without having an impact on the world around you.", author: "Jane Goodall" },
  { text: "What you do makes a difference, and you have to decide what kind of difference you want to make.", author: "Jane Goodall" },
  { text: "The environment is where we all meet; where we all have a mutual interest; it is the one thing all of us share.", author: "Lady Bird Johnson" },
  { text: "Every day is Earth Day.", author: "Anonymous" },
  { text: "Nature does not hurry, yet everything is accomplished.", author: "Lao Tzu" },
  { text: "The future will be green, or not at all.", author: "Jonathon Porritt" },
  { text: "Live simply so that others may simply live.", author: "Mahatma Gandhi" },
  { text: "There is no Planet B.", author: "Anonymous" },
  { text: "Be the change you wish to see in the world.", author: "Mahatma Gandhi" },
  { text: "The most sustainable garment is the one already in your wardrobe.", author: "Anonymous" },
  { text: "Reuse, reduce, recycle, refuse.", author: "Anonymous" },
  { text: "Every time you spend money, you're casting a vote for the kind of world you want.", author: "Anna Lappé" },
  { text: "Buy less, choose well, make it last.", author: "Vivienne Westwood" },
  { text: "The Earth is what we all have in common.", author: "Wendell Berry" },
  { text: "Progress is impossible without change, and those who cannot change their minds cannot change anything.", author: "George Bernard Shaw" },
  { text: "One person can make a difference, and everyone should try.", author: "John F. Kennedy" },
  { text: "The only way forward, if we are going to improve the quality of the environment, is to get everybody involved.", author: "Richard Rogers" },
  { text: "Start where you are. Use what you have. Do what you can.", author: "Arthur Ashe" },
  { text: "Never doubt that a small group of thoughtful, committed citizens can change the world; indeed, it's the only thing that ever has.", author: "Margaret Mead" },
  { text: "The best way to predict the future is to create it.", author: "Abraham Lincoln" },
  { text: "Small changes can make a big difference.", author: "Anonymous" },
  { text: "Sustainability is not a choice, it's a necessity for a better tomorrow.", author: "Anonymous" },
  { text: "The Earth does not belong to us; we belong to the Earth.", author: "Chief Seattle" },
  { text: "We do not inherit the Earth from our ancestors; we borrow it from our children.", author: "Native American Proverb" },
  { text: "The greatest threat to our planet is the belief that someone else will save it.", author: "Robert Swan" },
  { text: "You cannot get through a single day without having an impact on the world around you.", author: "Jane Goodall" },
  { text: "What you do makes a difference, and you have to decide what kind of difference you want to make.", author: "Jane Goodall" },
  { text: "The environment is where we all meet; where we all have a mutual interest; it is the one thing all of us share.", author: "Lady Bird Johnson" },
  { text: "Every day is Earth Day.", author: "Anonymous" },
  { text: "Nature does not hurry, yet everything is accomplished.", author: "Lao Tzu" },
  { text: "The future will be green, or not at all.", author: "Jonathon Porritt" },
  { text: "Live simply so that others may simply live.", author: "Mahatma Gandhi" },
  { text: "There is no Planet B.", author: "Anonymous" },
  { text: "Be the change you wish to see in the world.", author: "Mahatma Gandhi" },
  { text: "The most sustainable garment is the one already in your wardrobe.", author: "Anonymous" },
  { text: "Reuse, reduce, recycle, refuse.", author: "Anonymous" },
  { text: "Every time you spend money, you're casting a vote for the kind of world you want.", author: "Anna Lappé" },
  { text: "Buy less, choose well, make it last.", author: "Vivienne Westwood" },
  { text: "The Earth is what we all have in common.", author: "Wendell Berry" },
  { text: "Progress is impossible without change, and those who cannot change their minds cannot change anything.", author: "George Bernard Shaw" },
  { text: "One person can make a difference, and everyone should try.", author: "John F. Kennedy" },
  { text: "The only way forward, if we are going to improve the quality of the environment, is to get everybody involved.", author: "Richard Rogers" },
  { text: "Start where you are. Use what you have. Do what you can.", author: "Arthur Ashe" },
  { text: "Never doubt that a small group of thoughtful, committed citizens can change the world; indeed, it's the only thing that ever has.", author: "Margaret Mead" },
  { text: "The best way to predict the future is to create it.", author: "Abraham Lincoln" },
  { text: "Small changes can make a big difference.", author: "Anonymous" },
  { text: "Sustainability is not a choice, it's a necessity for a better tomorrow.", author: "Anonymous" },
  { text: "The Earth does not belong to us; we belong to the Earth.", author: "Chief Seattle" },
  { text: "We do not inherit the Earth from our ancestors; we borrow it from our children.", author: "Native American Proverb" },
  { text: "The greatest threat to our planet is the belief that someone else will save it.", author: "Robert Swan" },
  { text: "You cannot get through a single day without having an impact on the world around you.", author: "Jane Goodall" },
  { text: "What you do makes a difference, and you have to decide what kind of difference you want to make.", author: "Jane Goodall" },
  { text: "The environment is where we all meet; where we all have a mutual interest; it is the one thing all of us share.", author: "Lady Bird Johnson" },
  { text: "Every day is Earth Day.", author: "Anonymous" },
  { text: "Nature does not hurry, yet everything is accomplished.", author: "Lao Tzu" },
  { text: "The future will be green, or not at all.", author: "Jonathon Porritt" },
  { text: "Live simply so that others may simply live.", author: "Mahatma Gandhi" },
  { text: "There is no Planet B.", author: "Anonymous" },
  { text: "Be the change you wish to see in the world.", author: "Mahatma Gandhi" },
  { text: "The most sustainable garment is the one already in your wardrobe.", author: "Anonymous" },
  { text: "Reuse, reduce, recycle, refuse.", author: "Anonymous" },
  { text: "Every time you spend money, you're casting a vote for the kind of world you want.", author: "Anna Lappé" },
  { text: "Buy less, choose well, make it last.", author: "Vivienne Westwood" },
  { text: "The Earth is what we all have in common.", author: "Wendell Berry" },
  { text: "Progress is impossible without change, and those who cannot change their minds cannot change anything.", author: "George Bernard Shaw" },
  { text: "One person can make a difference, and everyone should try.", author: "John F. Kennedy" },
  { text: "The only way forward, if we are going to improve the quality of the environment, is to get everybody involved.", author: "Richard Rogers" },
  { text: "Start where you are. Use what you have. Do what you can.", author: "Arthur Ashe" },
  { text: "Never doubt that a small group of thoughtful, committed citizens can change the world; indeed, it's the only thing that ever has.", author: "Margaret Mead" },
  { text: "The best way to predict the future is to create it.", author: "Abraham Lincoln" },
  { text: "Small changes can make a big difference.", author: "Anonymous" },
  { text: "Sustainability is not a choice, it's a necessity for a better tomorrow.", author: "Anonymous" },
  { text: "The Earth does not belong to us; we belong to the Earth.", author: "Chief Seattle" },
  { text: "We do not inherit the Earth from our ancestors; we borrow it from our children.", author: "Native American Proverb" },
  { text: "The greatest threat to our planet is the belief that someone else will save it.", author: "Robert Swan" },
  { text: "You cannot get through a single day without having an impact on the world around you.", author: "Jane Goodall" },
  { text: "What you do makes a difference, and you have to decide what kind of difference you want to make.", author: "Jane Goodall" },
  { text: "The environment is where we all meet; where we all have a mutual interest; it is the one thing all of us share.", author: "Lady Bird Johnson" },
  { text: "Every day is Earth Day.", author: "Anonymous" },
  { text: "Nature does not hurry, yet everything is accomplished.", author: "Lao Tzu" },
  { text: "The future will be green, or not at all.", author: "Jonathon Porritt" },
  { text: "Live simply so that others may simply live.", author: "Mahatma Gandhi" },
  { text: "There is no Planet B.", author: "Anonymous" },
  { text: "Be the change you wish to see in the world.", author: "Mahatma Gandhi" },
  { text: "The most sustainable garment is the one already in your wardrobe.", author: "Anonymous" },
  { text: "Reuse, reduce, recycle, refuse.", author: "Anonymous" },
  { text: "Every time you spend money, you're casting a vote for the kind of world you want.", author: "Anna Lappé" },
  { text: "Buy less, choose well, make it last.", author: "Vivienne Westwood" },
  { text: "The Earth is what we all have in common.", author: "Wendell Berry" },
  { text: "Progress is impossible without change, and those who cannot change their minds cannot change anything.", author: "George Bernard Shaw" },
  { text: "One person can make a difference, and everyone should try.", author: "John F. Kennedy" },
  { text: "The only way forward, if we are going to improve the quality of the environment, is to get everybody involved.", author: "Richard Rogers" },
  { text: "Start where you are. Use what you have. Do what you can.", author: "Arthur Ashe" },
  { text: "Never doubt that a small group of thoughtful, committed citizens can change the world; indeed, it's the only thing that ever has.", author: "Margaret Mead" },
  { text: "The best way to predict the future is to create it.", author: "Abraham Lincoln" },
  { text: "Small changes can make a big difference.", author: "Anonymous" },
  { text: "Sustainability is not a choice, it's a necessity for a better tomorrow.", author: "Anonymous" },
  { text: "The Earth does not belong to us; we belong to the Earth.", author: "Chief Seattle" },
  { text: "We do not inherit the Earth from our ancestors; we borrow it from our children.", author: "Native American Proverb" },
  { text: "The greatest threat to our planet is the belief that someone else will save it.", author: "Robert Swan" },
  { text: "You cannot get through a single day without having an impact on the world around you.", author: "Jane Goodall" },
  { text: "What you do makes a difference, and you have to decide what kind of difference you want to make.", author: "Jane Goodall" },
  { text: "The environment is where we all meet; where we all have a mutual interest; it is the one thing all of us share.", author: "Lady Bird Johnson" },
  { text: "Every day is Earth Day.", author: "Anonymous" },
  { text: "Nature does not hurry, yet everything is accomplished.", author: "Lao Tzu" },
  { text: "The future will be green, or not at all.", author: "Jonathon Porritt" },
  { text: "Live simply so that others may simply live.", author: "Mahatma Gandhi" },
  { text: "There is no Planet B.", author: "Anonymous" },
  { text: "Be the change you wish to see in the world.", author: "Mahatma Gandhi" },
  { text: "The most sustainable garment is the one already in your wardrobe.", author: "Anonymous" },
  { text: "Reuse, reduce, recycle, refuse.", author: "Anonymous" },
  { text: "Every time you spend money, you're casting a vote for the kind of world you want.", author: "Anna Lappé" },
  { text: "Buy less, choose well, make it last.", author: "Vivienne Westwood" },
  { text: "The Earth is what we all have in common.", author: "Wendell Berry" },
  { text: "Progress is impossible without change, and those who cannot change their minds cannot change anything.", author: "George Bernard Shaw" },
  { text: "One person can make a difference, and everyone should try.", author: "John F. Kennedy" },
  { text: "The only way forward, if we are going to improve the quality of the environment, is to get everybody involved.", author: "Richard Rogers" },
  { text: "Start where you are. Use what you have. Do what you can.", author: "Arthur Ashe" },
  { text: "Never doubt that a small group of thoughtful, committed citizens can change the world; indeed, it's the only thing that ever has.", author: "Margaret Mead" },
  { text: "The best way to predict the future is to create it.", author: "Abraham Lincoln" },
  { text: "Small changes can make a big difference.", author: "Anonymous" },
  { text: "Sustainability is not a choice, it's a necessity for a better tomorrow.", author: "Anonymous" },
  { text: "The Earth does not belong to us; we belong to the Earth.", author: "Chief Seattle" },
  { text: "We do not inherit the Earth from our ancestors; we borrow it from our children.", author: "Native American Proverb" },
  { text: "The greatest threat to our planet is the belief that someone else will save it.", author: "Robert Swan" },
  { text: "You cannot get through a single day without having an impact on the world around you.", author: "Jane Goodall" },
  { text: "What you do makes a difference, and you have to decide what kind of difference you want to make.", author: "Jane Goodall" },
  { text: "The environment is where we all meet; where we all have a mutual interest; it is the one thing all of us share.", author: "Lady Bird Johnson" },
  { text: "Every day is Earth Day.", author: "Anonymous" },
  { text: "Nature does not hurry, yet everything is accomplished.", author: "Lao Tzu" },
  { text: "The future will be green, or not at all.", author: "Jonathon Porritt" },
  { text: "Live simply so that others may simply live.", author: "Mahatma Gandhi" },
  { text: "There is no Planet B.", author: "Anonymous" },
  { text: "Be the change you wish to see in the world.", author: "Mahatma Gandhi" },
  { text: "The most sustainable garment is the one already in your wardrobe.", author: "Anonymous" },
  { text: "Reuse, reduce, recycle, refuse.", author: "Anonymous" },
  { text: "Every time you spend money, you're casting a vote for the kind of world you want.", author: "Anna Lappé" },
  { text: "Buy less, choose well, make it last.", author: "Vivienne Westwood" },
  { text: "The Earth is what we all have in common.", author: "Wendell Berry" },
  { text: "Progress is impossible without change, and those who cannot change their minds cannot change anything.", author: "George Bernard Shaw" },
  { text: "One person can make a difference, and everyone should try.", author: "John F. Kennedy" },
  { text: "The only way forward, if we are going to improve the quality of the environment, is to get everybody involved.", author: "Richard Rogers" },
  { text: "Start where you are. Use what you have. Do what you can.", author: "Arthur Ashe" },
  { text: "Never doubt that a small group of thoughtful, committed citizens can change the world; indeed, it's the only thing that ever has.", author: "Margaret Mead" }
  
];

const DailyQuote = () => {
  const [quote, setQuote] = useState({ text: "", author: "" });

  useEffect(() => {
    const getQuoteForToday = async () => {
      try {
        // Get the current date string
        const today = new Date().toDateString();
        
        // Check if we already have a quote for today
        const storedDate = await AsyncStorage.getItem("quoteDate");
        
        if (storedDate !== today) {
          // It's a new day, select a new quote
          const randomIndex = Math.floor(Math.random() * quotes.length);
          const todaysQuote = quotes[randomIndex];
          
          // Save the new quote and today's date
          await AsyncStorage.setItem("currentQuote", JSON.stringify(todaysQuote));
          await AsyncStorage.setItem("quoteDate", today);
          
          setQuote(todaysQuote);
        } else {
          // Get the stored quote for today
          const storedQuote = await AsyncStorage.getItem("currentQuote");
          if (storedQuote) {
            setQuote(JSON.parse(storedQuote));
          } else {
            // Fallback if stored quote not found
            const randomIndex = Math.floor(Math.random() * quotes.length);
            setQuote(quotes[randomIndex]);
          }
        }
      } catch (error) {
        console.error("Error getting daily quote:", error);
        // Fallback to a random quote if error occurs
        const randomIndex = Math.floor(Math.random() * quotes.length);
        setQuote(quotes[randomIndex]);
      }
    };

    getQuoteForToday();
  }, []);

  if (!quote.text) {
    return null; // Don't render anything if the quote isn't loaded yet
  }

  return (
    <View style={styles.quoteContainer}>
      <View style={styles.quoteIconContainer}>
        <Ionicons name="chatbubble-ellipses" size={24} color="#4CAF50" />
      </View>
      <View style={styles.quoteTextContainer}>
        <Text style={styles.quoteText}>"{quote.text}"</Text>
        <Text style={styles.quoteAuthor}>— {quote.author}</Text>
      </View>
    </View>
  );
};

const styles = StyleSheet.create({
  quoteContainer: {
    backgroundColor: "#ffffff",
    borderRadius: 16,
    padding: 20,
    flexDirection: "row",
    marginBottom: 24,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  quoteIconContainer: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: "#e0f7e9",
    justifyContent: "center",
    alignItems: "center",
    marginRight: 16,
  },
  quoteTextContainer: {
    flex: 1,
  },
  quoteText: {
    fontSize: 16,
    fontStyle: "italic",
    color: "#333333",
    marginBottom: 8,
    lineHeight: 22,
  },
  quoteAuthor: {
    fontSize: 14,
    fontWeight: "600",
    color: "#4CAF50",
    textAlign: "right",
  },
});

export default DailyQuote;