import { Platform } from "react-native";
import { useTheme } from "../contexts/ThemeContext"; // Adjust path if needed

export const useProfileStyles = () => {
  const theme = useTheme();

  return {
    container: {
      flex: 1,
      backgroundColor: theme.backgroundPrimary,
    },
    scrollContainer: {
      flexGrow: 1,
      paddingBottom: 24,
    },
    header: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      paddingHorizontal: 16,
      paddingVertical: 16,
      backgroundColor: theme.backgroundSecondary,
    },
    backButton: {
      padding: 8,
    },
    headerTitle: {
      fontSize: 18,
      fontWeight: "600",
      color: theme.textPrimary,
    },
    // Hero section with profile image and name
    heroSection: {
      alignItems: "center",
      paddingVertical: 24,
      paddingHorizontal: 16,
      backgroundColor: theme.backgroundSecondary,
      borderBottomLeftRadius: 24,
      borderBottomRightRadius: 24,
      shadowColor: "#000",
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.1,
      shadowRadius: 4,
      elevation: 3,
      marginBottom: 16,
    },
    profileImageContainer: {
      position: "relative",
      width: 108,
      height: 108,
      marginBottom: 16,
    },
    profileImageBg: {
      width: 108,
      height: 108,
      borderRadius: 54,
      backgroundColor: theme.inputBackground,
      justifyContent: "center",
      alignItems: "center",
      overflow: "hidden",
      borderWidth: 4,
      borderColor: theme.backgroundPrimary,
    },
    profileImage: {
      width: 100,
      height: 100,
      borderRadius: 50,
    },
    cameraButton: {
      position: "absolute",
      bottom: 0,
      right: 0,
      backgroundColor: theme.primary,
      padding: 8,
      borderRadius: 18,
      borderWidth: 3,
      borderColor: theme.backgroundPrimary,
      justifyContent: "center",
      alignItems: "center",
    },
    nameContainer: {
      flexDirection: "row",
      alignItems: "center",
      marginTop: 8,
    },
    userName: {
      fontSize: 24,
      fontWeight: "bold",
      color: theme.textPrimary,
      marginRight: 8,
    },
    editNameButton: {
      padding: 4,
    },
    nameEditContainer: {
      width: "80%",
      marginTop: 8,
      marginBottom: 8,
    },
    nameInput: {
      borderWidth: 1,
      borderColor: theme.border,
      padding: 12,
      borderRadius: 12,
      fontSize: 16,
      color: theme.textPrimary,
      backgroundColor: theme.inputBackground,
      marginBottom: 8,
    },
    editButtonsRow: {
      flexDirection: "row",
      justifyContent: "flex-end",
    },
    cancelButton: {
      padding: 8,
      borderRadius: 8,
      backgroundColor: theme.backgroundSecondary,
      marginRight: 8,
    },
    saveButton: {
      backgroundColor: theme.primary,
      padding: 8,
      borderRadius: 8,
    },
    userRole: {
      fontSize: 16,
      color: theme.textSecondary,
      marginTop: 4,
    },
    // Score card
    scoreCard: {
      backgroundColor: theme.backgroundSecondary,
      borderRadius: 16,
      padding: 16,
      marginHorizontal: 16,
      marginVertical: 16,
      shadowColor: "#000",
      shadowOffset: { width: 0, height: 1 },
      shadowOpacity: 0.1,
      shadowRadius: 3,
      elevation: 2,
    },
    scoreHeader: {
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "center",
      marginBottom: 12,
    },
    scoreTitle: {
      fontSize: 16,
      fontWeight: "600",
      color: theme.textPrimary,
    },
    scoreValue: {
      fontSize: 16,
      fontWeight: "bold",
      color: theme.primary,
    },
    progressContainer: {
      height: 8,
      backgroundColor: theme.border,
      borderRadius: 4,
      marginBottom: 12,
      overflow: "hidden",
    },
    progressBar: {
      height: 8,
      backgroundColor: theme.primary,
      borderRadius: 4,
    },
    scoreDescription: {
      fontSize: 14,
      color: theme.textSecondary,
      marginTop: 4,
    },
    // Section title
    sectionTitle: {
      fontSize: 18,
      fontWeight: "600",
      color: theme.textPrimary,
      marginBottom: 16,
      paddingHorizontal: 16,
    },
    // Options
    optionsContainer: {
      marginTop: 8,
      paddingHorizontal: 16,
    },
    optionButton: {
      flexDirection: "row",
      alignItems: "center",
      backgroundColor: theme.backgroundSecondary,
      paddingVertical: 16,
      paddingHorizontal: 16,
      borderRadius: 12,
      marginBottom: 12,
    },
    optionIconContainer: {
      width: 40,
      height: 40,
      borderRadius: 20,
      justifyContent: "center",
      alignItems: "center",
      marginRight: 16,
    },
    optionLabel: {
      flex: 1,
      fontSize: 16,
      fontWeight: "500",
      color: theme.textPrimary,
    },
    chevronIcon: {
      opacity: 0.7,
    },
    // Logout
    logoutContainer: {
      paddingVertical: 16,
      paddingHorizontal: 16,
      justifyContent: "center",
      alignItems: "center",
      marginTop: 8,
    },
    logoutButton: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "center",
      paddingVertical: 12,
      paddingHorizontal: 24,
      backgroundColor: theme.errorBackground || "#FFEBEE",
      borderRadius: 12,
      width: "100%",
    },
    logoutIcon: {
      marginRight: 8,
    },
    logoutText: {
      color: theme.error || "#D32F2F",
      fontSize: 16,
      fontWeight: "500",
    },
    // Modal styles
    modalOverlay: {
      flex: 1,
      backgroundColor: "rgba(0,0,0,0.5)",
      justifyContent: "flex-end",
    },
    modalContent: {
      backgroundColor: theme.backgroundPrimary,
      borderTopLeftRadius: 24,
      borderTopRightRadius: 24,
      paddingBottom: Platform.OS === "ios" ? 36 : 24,
      maxHeight: "85%",
    },
    modalHeader: {
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "center",
      paddingHorizontal: 20,
      paddingVertical: 16,
      borderBottomWidth: 1,
      borderBottomColor: theme.border,
    },
    modalTitle: {
      fontSize: 18,
      fontWeight: "600",
      color: theme.textPrimary,
    },
    modalFooter: {
      flexDirection: "row",
      justifyContent: "space-between",
      paddingHorizontal: 20,
      paddingTop: 16,
    },
    // Support modal styles
    supportContent: {
      padding: 20,
      maxHeight: 400,
    },
    supportCard: {
      backgroundColor: theme.backgroundSecondary,
      borderRadius: 16,
      padding: 20,
      marginBottom: 16,
      alignItems: "center",
    },
    supportIcon: {
      marginBottom: 16,
    },
    supportText: {
      fontSize: 18,
      fontWeight: "600",
      color: theme.textPrimary,
      marginBottom: 8,
    },
    supportPhone: {
      fontSize: 16,
      color: theme.primary,
      fontWeight: "500",
      marginBottom: 8,
    },
    supportEmail: {
      fontSize: 16,
      color: theme.primary,
      fontWeight: "500",
      marginBottom: 8,
    },
    supportHours: {
      fontSize: 14,
      color: theme.textSecondary,
      textAlign: "center",
    },
    supportFaq: {
      fontSize: 14,
      color: theme.textSecondary,
      textAlign: "center",
    },
    // Feedback modal styles
    feedbackContent: {
      padding: 20,
    },
    feedbackIcon: {
      alignSelf: "center",
      marginBottom: 16,
    },
    feedbackIntro: {
      fontSize: 14,
      color: theme.textSecondary,
      marginBottom: 16,
      textAlign: "center",
    },
    feedbackInput: {
      borderWidth: 1,
      borderColor: theme.border,
      borderRadius: 12,
      padding: 16,
      color: theme.textPrimary,
      backgroundColor: theme.inputBackground,
      height: 150,
      fontSize: 15,
    },
    feedbackTypeContainer: {
      flexDirection: "row",
      flexWrap: "wrap",
      marginTop: 8,
      justifyContent: "space-between",
    },
    feedbackTypeButton: {
      backgroundColor: theme.backgroundSecondary,
      paddingVertical: 8,
      paddingHorizontal: 12,
      borderRadius: 8,
      marginBottom: 8,
      borderWidth: 1,
      borderColor: theme.border,
      minWidth: "48%",
      alignItems: "center",
    },
    feedbackTypeText: {
      color: theme.textPrimary,
      fontSize: 14,
      fontWeight: "500",
    },
    // Password modal styles
    passwordContent: {
      padding: 20,
    },
    passwordIcon: {
      alignSelf: "center",
      marginBottom: 16,
    },
    passwordIntro: {
      fontSize: 14,
      color: theme.textSecondary,
      marginBottom: 16,
      textAlign: "center",
    },
    passwordField: {
      marginBottom: 16,
    },
    formLabel: {
      fontSize: 14,
      fontWeight: "500",
      color: theme.textPrimary,
      marginBottom: 8,
    },
    passwordInputContainer: {
      flexDirection: "row",
      alignItems: "center",
      borderWidth: 1,
      borderColor: theme.border,
      borderRadius: 12,
      paddingHorizontal: 16,
      backgroundColor: theme.inputBackground,
    },
    passwordInput: {
      flex: 1,
      paddingVertical: 12,
      color: theme.textPrimary,
    },
    passwordRequirements: {
      marginTop: 16,
      marginBottom: 24,
    },
    passwordRequirementsTitle: {
      fontSize: 14,
      fontWeight: "500",
      color: theme.textPrimary,
      marginBottom: 12,
    },
    requirementItem: {
      flexDirection: "row",
      alignItems: "center",
      marginBottom: 8,
    },
    requirementText: {
      fontSize: 14,
      color: theme.textSecondary,
      marginLeft: 8,
    },
    // Button styles
    primaryButton: {
      backgroundColor: theme.primary,
      paddingVertical: 14,
      paddingHorizontal: 24,
      borderRadius: 12,
      flex: 1,
      alignItems: "center",
      justifyContent: "center",
      marginLeft: 8,
    },
    primaryButtonText: {
      color: theme.textOnPrimary,
      fontSize: 16,
      fontWeight: "600",
    },
    secondaryButton: {
      backgroundColor: theme.backgroundSecondary,
      paddingVertical: 14,
      paddingHorizontal: 24,
      borderRadius: 12,
      flex: 1,
      alignItems: "center",
      justifyContent: "center",
      marginRight: 8,
    },
    secondaryButtonText: {
      color: theme.textPrimary,
      fontSize: 16,
      fontWeight: "500",
    },
    // Loading overlay
    loadingOverlay: {
      ...Platform.select({
        ios: {
          position: "absolute",
          top: 0,
          bottom: 0,
          left: 0,
          right: 0,
          backgroundColor: "rgba(0,0,0,0.3)",
          justifyContent: "center",
          alignItems: "center",
          zIndex: 1000,
        },
        android: {
          position: "absolute",
          top: 0,
          bottom: 0,
          left: 0,
          right: 0,
          backgroundColor: "rgba(0,0,0,0.3)",
          justifyContent: "center",
          alignItems: "center",
          elevation: 10,
        },
        default: {
          position: "absolute",
          top: 0,
          bottom: 0,
          left: 0,
          right: 0,
          backgroundColor: "rgba(0,0,0,0.3)",
          justifyContent: "center",
          alignItems: "center",
          zIndex: 1000,
        },
      }),
    },
  };
};